### PR TITLE
feat - trash and archive page

### PR DESCRIPTION
**Pull request by prachi-sahani**
This PR includes the following features and changes:
 - archive page
   - user can unarchive and perform other actions on this page
 - trash page
   - user can restore or permanently delete the note
 - separate component "zero notes page"
 - some basic refactoring
    - moved footer icons in "add note" page to new component
    - moved note card in "view notes page" to a separate component  
    
image
image

image

### CODE REVIEW

**Review by MaruthiPothuganti — COMMENTED** [review]
Everything works as Specified(as Expected). Code looks clean too.
One Suggestion- Add a **title** attribute for the icons so that user actually knows what he is doing beforehand. 
- For example in _Trash_  section, as the icons are small. It is bit diffiult to distinguish the icon operation.

**Review by shivampandey0 — APPROVED** [review]
Overall neat code written
Good use of routes, context, and component structure.

Suggestion:
- As pointed out by another reviewer `title` for icons will be helpful for users to understand the actions of different icons.

**Comment by prachi-sahani** [comment]
> Everything works as Specified(as Expected). Code looks clean too. One Suggestion- Add a **title** attribute for the icons so that user actually knows what he is doing beforehand.
> 
> * For example in _Trash_  section, as the icons are small. It is bit difficult to distinguish the icon operation.

Done. Thanks!

**Comment by prachi-sahani** [comment]
> Overall neat code written Good use of routes, context, and component structure.
> 
> Suggestion:
> 
> * As pointed out by another reviewer `title` for icons will be helpful for users to understand the actions of different icons.

Done. Thanks!

**Pull request merged**
